/**
 * @file    error_handler.h
 * @author  l.heywang <leonard.heywang@proton.me>
 * @brief   Header file the error handler. Depends on the ST HAL library.
 * 			Some code here is generated by CubeMX.
 * @version 0.1
 * @date    2026-02-21
 *
 * @copyright Copyright (c) 2026
 *
 */

// ======================================================================
//                              INCLUDES
// ======================================================================
// Local library
#include "stm32h5xx_hal.h"

// ======================================================================
//                              FUNCTIONS
// ======================================================================

/**
 * @brief  This function is executed in case of error occurrence.
 * @retval None
 */
void Error_Handler(void);
