/**
 * @file    hal_it.c
 * @author  l.heywang <leonard.heywang@proton.me>
 * @brief   Source file the HAL managed interrupts. Depends on the ST HAL
 * library. Some code here is generated by CubeMX.
 * @version 0.1
 * @date    2026-02-21
 *
 * @copyright Copyright (c) 2026
 *
 */

// ======================================================================
//                              INCLUDES
// ======================================================================
// Local library
#include "stm32h5xx_hal.h"

// ======================================================================
//                              FUNCTIONS
// ======================================================================

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
    if (htim->Instance == TIM6) {
        HAL_IncTick();
    }
}
