/**
 * @file    error_handler.c
 * @author  l.heywang <leonard.heywang@proton.me>
 * @brief   Source file the error handler. Depends on the ST HAL library.
 * 			Some code here is generated by CubeMX.
 * @version 0.1
 * @date    2026-02-21
 *
 * @copyright Copyright (c) 2026
 *
 */

// ======================================================================
//                              INCLUDES
// ======================================================================
// Local library
#include "stm32h5xx_hal.h"

// ======================================================================
//                              FUNCTIONS
// ======================================================================

/**
 * @brief  This function is executed in case of error occurrence.
 * @retval None
 */
void Error_Handler(void) {
    /* USER CODE BEGIN Error_Handler_Debug */
    /* User can add his own implementation to report the HAL error return state */
    __disable_irq();
    while (1) {
    }
    /* USER CODE END Error_Handler_Debug */
}
