/**
 * @file    hal_it.h
 * @author  l.heywang <leonard.heywang@proton.me>
 * @brief   Header file the HAL managed interrupts. Depends on the ST HAL
 * library. Some code here is generated by CubeMX.
 * @version 0.1
 * @date    2026-02-21
 *
 * @copyright Copyright (c) 2026
 *
 */

#pragma once

// ======================================================================
//                              INCLUDES
// ======================================================================
// Local library
#include "stm32h5xx_hal.h"

// STD
#include <stdint.h>

// ======================================================================
//                              FUNCTIONS
// ======================================================================

/**
 * @brief  Period elapsed callback in non blocking mode
 * @note   This function is called  when TIM6 interrupt took place, inside
 * HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment
 * a global variable "uwTick" used as application time base.
 * @param  htim : TIM handle
 * @retval None
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim);
